### ISSUE TITLE
Soak Test 2020-12-08 V 2020.12.8.4

### ISSUE THREAD

**Issue by MicroTrendsTom** [MicroTrendsLtd/NinjaTrader8#25]
reversal
1 Second Chart
Debug open in VS Studio
Detailed Tracing 
![image](https://user-images.githubusercontent.com/24366913/101519619-66841b00-3951-11eb-8cd8-214d2765ad4e.png)
Will turn this on for about 8 hours then a scheduled connect to the same datafeed will stop the strategy and we will also look for issues on that event

**Comment by jmscraig** [comment]
I noticed neither Q related bool is enabled.  

Will you be testing with the no Q enabled?, default Q?, all kinds of Q state tests?

**Comment by jmscraig** [comment]
Somewhere Tom posted ~~"that he felt possibly that running strategies headless (without a chart) is more reliable because of client workload pressures and complexities. "   .. or something like that

Beyond that Strategy instantiation or restart can sometimes be different between running from a chart and not, I am guessing this a least sometimes has something to do with what we include in OSC() and what OSC() state we land it in.

This surfaces the question "Could OSC() configuration design be a contributor to occasional reliability concerns?"

**Comment by MicroTrendsTom** [comment]
Results all good - no lock up on 1 Second Reversal strategy
VS 2019 debug break start/pause no locks
Chart  no deadlocks - NT8 no Deadlocks
Trace file no locks or or unhandled exceptions
No exception on disconnect
Can reconnect and continue if desired
![image](https://user-images.githubusercontent.com/24366913/101569221-09fd1c00-39a2-11eb-862a-5127c91d9abd.png)

![image](https://user-images.githubusercontent.com/24366913/101569257-239e6380-39a2-11eb-8ab3-088fd646d647.png)

**Comment by MicroTrendsTom** [comment]
> I noticed neither Q related bool is enabled.
>  Will you be testing with no Q enabled?, default Q?, a variety of Q state tests?

This would need to be tested but today i have to use the current version of the Engine and finish off a project using it and so testing the Q wont be on the agenda - as yet etc but for sure it needs to be done
