### ISSUE TITLE
Greetings!

### ISSUE THREAD

**Issue by jmscraig** [MicroTrendsLtd/NinjaTrader8#48]
Hi Tom,

This is not really an issue.. please close it.

When I saw this I thought you might have interest in it so came by to drop this link..  https://github.com/rpraka/ChartATM

JC

**Comment by MicroTrendsTom** [comment]
Sorry i dont view or look at 3rd party components due to copyright and so on- and the fact the enjoyment is inventing and creating not copying or being influenced. e.g. creating features based from knowledge of what is needed etc

Did you know - in 2009 onwards MicroTrends was the pioneer of Chart Base UI Hybrid  trading Systems and this type of trading engine so we are in good hand,  all of the software was in fact taken off the market to allow me to trade and also due to daylight thievery and reverse engineering by other vendors in the NT Ecosystem  - to cut a long story short -  the only current software we have that will give you some idea of what it was like is here  https://algofuturestrader.com/
and what it will be like once again if i can ever find time for NT8 versions  etc

**Comment by MicroTrendsTom** [comment]
this discussion has stirred me into action please see discussion #50  which is about a chart trader UI and getting the other layers out for this engine

**Comment by jmscraig** [comment]
Cool!

**Comment by jmscraig** [comment]
> this discussion has stirred me into action please see discussion #50 which is about a chart trader UI and getting the other layers out for this engine - this is an example of how it will look etc
> 

I have still been thinking about building similar, though I was thinking about a companion UI window that would be less tied to just NT8 and the very limited brokerage and instrument offerings of NinjaTrader.  Something that becomes primary instead of NT8 but works well with NT8 when I want to focus on classic futures contracts.  

Tap me if you want some design banter or testing help. 

James 

![Tom's NT8-UI](https://user-images.githubusercontent.com/15313578/153734045-7b33b41f-fba3-4928-8e0b-b06f71121c26.JPG)

![AFT-NinjaBuddy-OverView](https://user-images.githubusercontent.com/15313578/153734055-c34db250-6d65-4c2f-994b-e6e5f73e55d6.png)
