### ISSUE TITLE
File Structure ATSQuadroStrategyBase.GUI Folder

### ISSUE THREAD

**Issue by TLable** [MicroTrendsLtd/NinjaTrader8#66]
As shown in the screenshot, the file structure to the ATSQuadroStrategyBase has similar structure to Ninja Trader 8 folder. Though in the Zip one level above alongside "ATSQuadroStrategyBase.GUI" & "ATSQuadroStrategyBase" folders, which inside the "ATSQuadroStrategyBase.GUI" folder has dissimilar fil structure to Ninja Trader 8 folder, and I ask what is the proper placement to the folder? Does it go on the same level as Ninja Trader 8 inside Documents, or do "ATSQuadroStrategyBase.GUI" folder files have a separate placement inside Documents>Ninja Trader 8 structure.

![Screenshot_265 (2)_LI](https://user-images.githubusercontent.com/49819999/172418900-6d28201e-d35d-4dd6-b721-74d630ad3710.jpg)
.

**Comment by MicroTrendsTom** [comment]
By your question it is obvious you are off the green and fairway into the woods and rough.
No where does it say to use or copy that other folder it only discusses 1 folder and shows 2 routes that both work. 

In theory this is basic 101 operating system skills with zip files, windows folders copy and paste and should takes about 30seconds to do: Download Zip, Extract, Browse to and Select source folder. Copy. browse to target folder paste over target - yes to copy.   So maybe the steps are unclear or the screenshots not clear we will need to understand what is not clear to remedy.

**Step 1 Install:**  Follow the exact step by step instructions here:  #61   
Use  2nd scenario with the zip file,  follow the  exact words and screenshots- for each step.. 
Go right through to the end - ignore all other items that are not discussed in the instructions. 

Step 2: Setup the code editor reference - See here #65 

Please Note If you cannot understand or  follow the steps - please say which step you are stuck on and what the issue is?
So we can have a win win and arrive at the solution.
