### ISSUE TITLE
Getting Compile error for UserControlNinjaBuddy\xaml\txt.cs

### ISSUE THREAD

**Issue by khajamoddin** [MicroTrendsLtd/NinjaTrader8#79]
NinjaScript File	Error	Code	Line	Column
UserControlNinjaBuddy\xaml\txt.cs	Missing partial modifier on declaration of type 'ATSQuadroStrategyBase.GUI.UserControlNinjaBuddy'; another partial declaration of this type exists	CS0260	32	18

I tried to modify the declaration and resolve the namespace, path etc. still gets the same error. 

Let me know if you had faced similar issue and how did you resolved it. 
![Screenshot_20221108_233655](https://user-images.githubusercontent.com/3285129/200691745-f5f7b846-302e-4dd9-b52b-fad1a0cb1793.png)

**Comment by MicroTrendsTom** [comment]
No reports of error before this likely to be some kind of local environmental issues internal to NT8 and the open source files etc

The only way to deal with it is from the first step and then log any errors at each step taken.
1) With a clean healthy install of  NT8 with no existing errors  - default install and location etc
2)Follow the exact install procedure on the read me  here: https://github.com/MicroTrendsLtd/NinjaTrader8
then compile
Any issues with those steps will provide the details and info needed to replicate/resolve
  -

**Comment by TLable** [comment]
I have the same error when I install fresh. It is saying there is missing file and the file it is saying is already in the dir.

**Comment by MicroTrendsTom** [comment]
That error is usually due to installing both projects instead of only 1 - 
If you follow the exact steps here with a clean install of  NT8
https://github.com/MicroTrendsLtd/NinjaTrader8

E.G:
Installation: https://github.com/MicroTrendsLtd/NinjaTrader8/discussions/61
NT8 Code Editor Setup: https://github.com/MicroTrendsLtd/NinjaTrader8/discussions/65

Note: This project targets developers so this would not be suitable for non developers.
